services:
  webapp:
    container_name: webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - $WEBAPP_PORT:$WEBAPP_PORT
    volumes:
      - /app/node_modules
      - ./webapp:/app
    working_dir: /app
    command: npx remix vite:dev --host 0.0.0.0 --port $WEBAPP_PORT
  db:
    container_name: db
    image: postgres:$POSTGRES_VERSION
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGPORT: $POSTGRES_PORT
  hasura:
    # https://hasura.io/docs/2.0/getting-started/docker-simple/
    container_name: hasura
    image: hasura/graphql-engine:v$HASURA_VERSION
    ports:
      - $HASURA_PORT:$HASURA_PORT
    restart: always
    environment:
      HASURA_GRAPHQL_SERVER_PORT: $HASURA_PORT
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/$POSTGRES_DB
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/$POSTGRES_DB
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    depends_on:
      - db
  otelcol:
    # https://opentelemetry.io/docs/collector/installation/#docker-compose
    container_name: otelcol
    image: otel/opentelemetry-collector-contrib:$OTELCOL_VERSION
    volumes:
      - ./otelcol.yaml:/etc/otelcol-contrib/config.yaml
    environment:
      - OTELCOL_GRPC_PORT=$OTELCOL_GRPC_PORT
      - OTELCOL_HTTP_PORT=$OTELCOL_HTTP_PORT
      - O2_GRPC_PORT=$O2_GRPC_PORT
      - O2_AUTH_TOKEN=$O2_AUTH_TOKEN
      - O2_ORG=$O2_ORG
      - O2_STREAM=$O2_STREAM
    depends_on:
      - o2
  o2:
    # https://openobserve.ai/docs/guide/quickstart/#self-hosted-installation
    container_name: o2
    image: public.ecr.aws/zinclabs/openobserve:v$O2_VERSION
    ports:
      - $O2_HTTP_PORT:$O2_HTTP_PORT
    environment:
      - ZO_ROOT_USER_EMAIL=$O2_USER
      - ZO_ROOT_USER_PASSWORD=$O2_PASSWORD
      - ZO_HTTP_PORT=$O2_HTTP_PORT
      - ZO_GRPC_PORT=$O2_GRPC_PORT
      # Send anonymous telemetry info for improving OpenObserve. You can disable by set it to false
      - ZO_TELEMETRY=false